### ISSUE TITLE
Read application configs from yaml config files

### ISSUE THREAD

**Issue by jjmark15** [jjmark15/warp-server#39]
# Background
Currently using DIY config loading mechanism.

# Requirements
- [x] vendor confy
  - [x] add option to not create config file if missing
  - [x] create separate GitHub actions pipeline running confy tests
- add command line argument to server application for config filepath
  - default to local dev if not passed?
  - [x] raise new card for this (#47)
- [x] pass path to config file as argument in `App::new`
  - [x] fail to start if cannot find config file
  - [x] use `App::new` instead of `from_ip_and_port` in functional test state
  - can probably collapse the two methods after this
- [x] read alternative configs from config files
  - create a config file per environment:
    - [x] local (for local running and unit tests)
    - [x] functional test
- [x] lose ability to override config value from environment variables for now
  - [x] raise new card to re-introduce this on completion of this card (#48)
- [x] raise card to try to merge `quiz_domain_mocks` package into `quiz_domain` (#49)

# Debates
### Pass the path in a command line argument
- [x] makes docker images non-reusable
  - could fix with an `entrypoint.sh` script that chooses which config file to use based on an environment variable

# Additional context
https://docs.rs/confy/0.4.0/confy/

## Confy
Confy is an appealingly simple library that offers the ability to load a config from a yaml or toml file based on a filepath or name.

Confy has issues:
- bug existing in the version of confy released to crates.io that means that the YAML feature has been broken for months - this called into question how well supported the library is
- trying to load a config file that does not exist creates the file. this is not configurable behaviour and was considered unacceptable behaviour for this application as it could disguise severe errors

Therefore, decided to vendor the library and then make changes. In the future, it may be decided to write a config library entirely from scratch but confy with a few modifications meets the requirements perfectly for now.

**Comment by jjmark15** [comment]
may have to vendor confy until https://github.com/rust-cli/confy/issues/32 is resolved

**Comment by jjmark15** [comment]
if we adapt confy:
- [ ] vendor confy
- [ ] modify load to allow configuration of whether or not file should be created if it does not exist
- [ ] create a new github action to test vendored confy

**Comment by Zykino** [comment]
Hello, like you I was a bit upset that confy was on a very low maintenance mode. I just joined the rust-cli group to try to keep the crate more up to date.
For your second point, it was also requested to be able to get the configuration filename. I did a Pull Request for that (https://github.com/rust-cli/confy/pull/36) and was wondering if it could fix your issue. Like you get the filename and check yourself if it exist or not before loading the configuration. Not the best workflow but working and easy to use for most projects.

Do not hesitate to reach to me and/or review the pull request.
